language: objective-c

xcode_workspace: DjangoConsumer.xcworkspace
xcode_scheme: DjangoConsumer
osx_image: xcode9.2
xcode_sdk: iphonesimulator11.2

rvm:
  - 2.5.0@DjangoConsumer --create

cache:
  directories:
    # Specifying only the used pods because the cache can't digest
    # the whole 1.4G master Specs repo...
    - ~/.cocoapods/repos/master/Specs/d/4/d/Alamofire-SwiftyJSON/
    - ~/.cocoapods/repos/master/Specs/d/8/6/Embassy/
    - ~/.cocoapods/repos/master/Specs/3/1/4/EnvoyAmbassador/
    - ~/.cocoapods/repos/master/Specs/b/7/8/SwiftDate/
    - ~/.rvm/

before_install:
  - gem install bundler
  # See https://github.com/travis-ci/travis-ci/issues/8978 for further information
  # on why this gem update --system is necessary.
  - gem update --system
  - bundle install

script:
  - set -o pipefail && xcodebuild clean build test -workspace DjangoConsumer.xcworkspace -scheme DjangoConsumer -destination 'platform=iOS Simulator,name=iPhone X,OS=latest' | xcpretty
