os: osx
language: objective-c

xcode_workspace: DjangoConsumer.xcworkspace
xcode_scheme: DjangoConsumer
osx_image: xcode11.3
xcode_sdk: iphonesimulator13.2
xcode_workspace: DjangoConsumer.xcworkspace
xcode_scheme: DjangoConsumer
xcode_destination: platform=iOS Simulator,OS=13.3,name=iPhone 11
  
cache:
  cocoapods: true
  directories:
    # # Caching the ruby which is required in .ruby-version.
    # # This can be removed as soon as the required version 
    # # is pre-installed on the current osx_image.
    - ~/.rvm/rubies/ruby-2.6.5
    - ~/.rvm/gems/ruby-2.6.5
    
    # Using the default bundler cache directive (like the 
    # cocoapods directive above) does not work because it caches 
    # '/Users/travis/build/JanNash/DjangoConsumer/vendor/bundle',
    # which is not the location where the gemset is going to
    # be installed.
    - ~/.rvm/gems/ruby-2.6.5@DjangoConsumer/

before_install:
  - rvm use 2.6.5@DjangoConsumer --create
  
install:
  - gem install bundler
  - bundle install
  - pod install
