language: objective-c

xcode_workspace: DjangoConsumer.xcworkspace
xcode_scheme: DjangoConsumer
osx_image: xcode10.1
xcode_sdk: iphonesimulator12.1

rvm:
  # # The required ruby-version, which is also declared in 
  # # .ruby-version. This should only be commented in when
  # # recreating the cache, i.e. when the cache was deleted 
  # # or when the version changes.
  - 2.6.5
  # # Unfortunately, the rvm directive is executed *before* 
  # # the cache is loaded. To avoid an unnecessary installation 
  # # of the above version, we explicitly tell rvm to use a 
  # # version which is pre-installed on the current osx_image.
  # # In before_install (when the cache is loaded), we tell 
  # # rvm the actual version and gemset we want to use.
  # #
  # # We have to do this explicitly here, else, travis will
  # # infer the version from .ruby-version, which would lead
  # # to an unnecessary installation as well.
  # - 2.4.3
  
cache:
  cocoapods: true
  directories:
    # # Caching the ruby which is required in .ruby-version.
    # # This can be removed as soon as the required version 
    # # is pre-installed on the current osx_image.
    - ~/.rvm/rubies/ruby-2.6.5
    - ~/.rvm/gems/ruby-2.6.5
    
    # Using the default bundler cache directive (like the 
    # cocoapods directive above) does not work because it caches 
    # '/Users/travis/build/JanNash/DjangoConsumer/vendor/bundle',
    # which is not the location where the gemset is going to
    # be installed.
    - ~/.rvm/gems/ruby-2.6.5@DjangoConsumer/

before_install:
  - rvm use 2.6.5@DjangoConsumer --create
  
install:
  - gem install bundler
  - bundle install
  - pod install

script:
  - set -o pipefail && xcodebuild clean build test -workspace DjangoConsumer.xcworkspace -scheme DjangoConsumer -destination 'platform=iOS Simulator,name=iPhone X,OS=latest' | xcpretty
