language: swift

xcode_workspace: DjangoRFAFInterface.xcworkspace
xcode_scheme: DjangoRFAFInterface
osx_image: xcode9.2
xcode_sdk: iphonesimulator11.2

cache:
  - bundler
  - cocoapods

install:
  - bundle install 
  - pod install

script:
  - set -o pipefail && xcodebuild clean build test -workspace DjangoRFAFInterface.xcworkspace -scheme DjangoRFAFInterface -destination 'platform=iOS Simulator,name=iPhone X,OS=latest' | xcpretty
